// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2BYVyqdUDm-1rwGIMLMPtJ04ivOY7h8',
    appId: '1:713135664965:web:2ebe8f9a45689c351dd82c',
    messagingSenderId: '713135664965',
    projectId: 'pasthelwparking',
    authDomain: 'pasthelwparking.firebaseapp.com',
    storageBucket: 'pasthelwparking.appspot.com',
    measurementId: 'G-0FSV2VNCRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTzLUWWRNoAQYFE-9k6gZFbpHx4d9DXQ',
    appId: '1:713135664965:android:2934f4c3550354951dd82c',
    messagingSenderId: '713135664965',
    projectId: 'pasthelwparking',
    storageBucket: 'pasthelwparking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsEhWCP8rPpH1YijG8jeH_BS4bty2_Jx4',
    appId: '1:713135664965:ios:5d5842eb10aa86991dd82c',
    messagingSenderId: '713135664965',
    projectId: 'pasthelwparking',
    storageBucket: 'pasthelwparking.appspot.com',
    iosClientId:
        '713135664965-mlfnq0bgrvcdsu28iajfpknev5racbdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasthelwparkingV1',
  );
}
